# Generated by Django 5.2.6 on 2025-09-23 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('class_img', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, choices=[('danger', 'Danger'), ('success', 'Success'), ('info', 'Info')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_fantasia', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('movil', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cuit', models.CharField(max_length=50)),
                ('logo', models.ImageField(default='default.jpg', upload_to='logos')),
                ('last_process', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Pantalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(default='', max_length=100)),
                ('vista', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RubroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.categoriaalerta')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=8)),
                ('valor', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
                ('abrev', models.CharField(max_length=5, unique=True, verbose_name='abrev')),
                ('signo', models.CharField(choices=[('D', 'Debe'), ('H', 'Haber'), ('I', 'Indistinto')], max_length=1, verbose_name='signo')),
                ('automatico', models.BooleanField(default=True, verbose_name='automatico')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='numero')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('abrev', models.CharField(max_length=5, unique=True, verbose_name='Abrev')),
                ('t_saldo', models.CharField(choices=[('D', 'Deudora'), ('H', 'Acreedora'), ('I', 'Indistinto'), ('d', 'Indistinto normalmente deudora'), ('h', 'Indistinto normalmente acreedora')], max_length=1, verbose_name='Tipo de saldo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.ciudad', verbose_name='ciudad')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('leido_cc', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_cc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_usuario_cc', to=settings.AUTH_USER_MODEL)),
                ('usuario_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_usuario_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('desc_abr', models.CharField(max_length=3)),
                ('cartera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.cartera')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('numero', models.IntegerField(default=0)),
                ('debe', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('vencimiento', models.DateField(default=django.utils.timezone.now, verbose_name='vencimiento')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.cartera')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.comprobante')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.empresa')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.municipio', verbose_name='municipio'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.pais'),
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('banos', models.IntegerField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.empresa', verbose_name='empresa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='landing.tipopropiedad')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='landing.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='codigo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.pais', verbose_name='pais')),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.provincia', verbose_name='provincia'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rubroUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.rubrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='AccesoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso', models.BooleanField()),
                ('alta', models.BooleanField()),
                ('baja', models.BooleanField()),
                ('modificar', models.BooleanField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.empresa')),
                ('pantalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.pantalla')),
                ('rubroUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.rubrousuario')),
            ],
        ),
        migrations.CreateModel(
            name='TareaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=100)),
                ('completada', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordenada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_ordenada_por_usuario', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
